# Generated by Django 4.0.3 on 2022-04-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_opportunity_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
    ]
