# Generated by Django 4.0.3 on 2022-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_opportunity_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='www',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
