# Generated by Django 4.0.3 on 2022-04-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_company_options_alter_opportunity_options_and_more'),
        ('crm', '0004_company_www'),
    ]

    operations = [
    ]
