# Generated by Django 4.0.3 on 2022-05-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_employee_office_number_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
