# Generated by Django 4.0.3 on 2022-05-08 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_opportunity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 21, 6, 16, 884426)),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.address'),
        ),
    ]
