# Generated by Django 4.0.3 on 2022-05-08 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_employee_end_date_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 21, 46, 46, 531899)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
