# Generated by Django 4.0.3 on 2022-05-14 16:05

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_employee_end_date_alter_employee_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(default=crm.models.Employee.get_one_year_from_today),
        ),
    ]
